version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    ports:
      - "5632:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin4687
      POSTGRES_DB: nestdb







